# Generated by Django 4.1.2 on 2022-10-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
